version: '3.8'
services:
  nginxcdn:
    container_name: nginxcdn
    restart: unless-stopped
    build: .
    ports:
      - "80:80"
    volumes:
      - ./images:/usr/share/nginx/html/images
    # Used in Reverse Proxy Setup
    #expose:
    #   - 80
    # Networks
    #networks:
    #  - reverse_proxy_network


# Used in a reverse proxy setup
# networks:
#   reverse_proxy_network:
#     name: reverse_proxy_network
#     external: true